declare module 'prismjs'
declare module 'prismjs/components/prism-c'
declare module 'prismjs/components/prism-cpp'
declare module 'prismjs/components/prism-javascript'
declare module 'prismjs/components/prism-typescript'
declare module 'prismjs/components/prism-python'
declare module 'prismjs/components/prism-go'
declare module 'prismjs/components/prism-java'
declare module 'prismjs/components/prism-rust'
declare module 'prismjs/components/prism-bash'
declare module 'prismjs/components/prism-json'
declare module 'prismjs/components/prism-markup'
declare module 'prismjs/components/prism-css'

